// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA594aKndzFX6tU01ac8NwqP5SBtMKKX4',
    appId: '1:474766975480:android:af9b22d979a5f2fa7ab60d',
    messagingSenderId: '474766975480',
    projectId: 'ssm-qr-code-backend',
    databaseURL: 'https://ssm-qr-code-backend-default-rtdb.firebaseio.com',
    storageBucket: 'ssm-qr-code-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHVghds1FfcoJaYQtAV6tm9SeGftd2Nqg',
    appId: '1:474766975480:ios:ee2bee66d94e55f67ab60d',
    messagingSenderId: '474766975480',
    projectId: 'ssm-qr-code-backend',
    databaseURL: 'https://ssm-qr-code-backend-default-rtdb.firebaseio.com',
    storageBucket: 'ssm-qr-code-backend.appspot.com',
    iosBundleId: 'com.example.hexView',
  );
}
